/**
 * GET /api/agent/download
 *
 * File download endpoint — converts buffered tool output into a downloadable
 * file with the correct Content-Disposition header.
 *
 * Designed to be called by:
 *   - IDE agents (Kiro, Cursor, Copilot) that need to save output to disk
 *   - The Chrome extension "Save to file" button
 *   - Direct browser download links
 *
 * Query parameters:
 *   toolId   — which tool generated the content (used for filename + MIME)
 *   format   — file extension: md | html | txt | json
 *   content  — base64-encoded content string
 *   filename — optional custom filename (without extension)
 *
 * The content is passed directly in the URL (base64) to avoid needing a
 * server-side storage layer. For large documents, callers should POST to
 * /api/agent/execute with buffered=true and use the returned downloadUrl.
 *
 * Max content size: ~500KB base64 ≈ ~375KB raw — sufficient for any
 * document generated by the tools.
 */

import { NextRequest } from 'next/server';
import { TOOL_MAP } from '@/lib/agent/registry';

export const runtime = 'edge';

/** Map file extension → MIME type */
const MIME_MAP: Record<string, string> = {
  md: 'text/markdown; charset=utf-8',
  html: 'text/html; charset=utf-8',
  txt: 'text/plain; charset=utf-8',
  json: 'application/json; charset=utf-8',
};

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, X-Hephaestus-Key',
};

export async function OPTIONS() {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);

  const toolId    = searchParams.get('toolId') ?? 'document';
  const format    = searchParams.get('format') ?? 'md';
  const b64       = searchParams.get('content');
  const customName = searchParams.get('filename');

  if (!b64) {
    return new Response(
      JSON.stringify({ error: 'Missing required query parameter: "content"' }),
      { status: 400, headers: { 'Content-Type': 'application/json', ...CORS_HEADERS } }
    );
  }

  // Decode base64 content
  let content: string;
  try {
    content = atob(b64);
  } catch {
    return new Response(
      JSON.stringify({ error: 'Invalid base64 in "content" parameter' }),
      { status: 400, headers: { 'Content-Type': 'application/json', ...CORS_HEADERS } }
    );
  }

  // If the tool outputs JSON (visual-builder), unwrap the html field
  if (format === 'html' && content.trim().startsWith('{')) {
    try {
      const parsed = JSON.parse(content) as { html?: string };
      if (parsed.html) content = parsed.html;
    } catch { /* use raw content */ }
  }

  // Build filename
  const tool = TOOL_MAP.get(toolId);
  const toolSlug = tool?.id ?? toolId;
  const dateSuffix = new Date().toISOString().split('T')[0];
  const filename = customName
    ? `${customName}.${format}`
    : `${toolSlug}-${dateSuffix}.${format}`;

  const mimeType = MIME_MAP[format] ?? 'text/plain; charset=utf-8';

  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': mimeType,
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': String(new TextEncoder().encode(content).length),
      'Cache-Control': 'no-cache',
      ...CORS_HEADERS,
    },
  });
}
