'use client';

import React, { useState, useRef, useEffect, useId } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, Eye, FileText, FileSignature, Save, Eraser, Calendar, User, AlignLeft, Plus, Trash2 } from 'lucide-react';
import { toJpeg } from 'html-to-image';
import { ThreeDViewer } from '@/components/core/ThreeDViewer';
import SignatureCanvas from 'react-signature-canvas';
import { useAgent } from '@/context/AgentContext';

interface Term {
  id: string;
  title: string;
  content: string;
}

interface TemplateDef {
  name: string;
  documentTitle: string;
  intro: string;
  terms: Term[];
}

const TEMPLATES: Record<string, TemplateDef> = {
  nda: {
    name: 'Non-Disclosure',
    documentTitle: 'NON-DISCLOSURE AGREEMENT',
    intro: 'This Non-Disclosure Agreement (the "Agreement") is entered into as of {date} (the "Effective Date") by and between:\n\nDisclosing Party: {partyA}\nReceiving Party: {partyB}',
    terms: [
      { id: 'nda1', title: 'Definition of Confidential Information', content: '"Confidential Information" means any data or information that is proprietary to the Disclosing Party and not generally known to the public, whether in tangible or intangible form.' },
      { id: 'nda2', title: 'Obligations of Receiving Party', content: 'The Receiving Party shall hold and maintain the Confidential Information in strictest confidence for the sole and exclusive benefit of the Disclosing Party. The Receiving Party shall carefully restrict access to Confidential Information to employees, contractors and third parties as is reasonably required.' },
      { id: 'nda3', title: 'Term', content: `The nondisclosure provisions of this Agreement shall survive the termination of this Agreement and Receiving Party\\'s duty to hold Confidential Information in confidence shall remain in effect until the Confidential Information no longer qualifies as a trade secret or until Disclosing Party sends written notice releasing Receiving Party from this Agreement, whichever occurs first.` }
    ]
  },
  contractor: {
    name: 'Independent Contractor',
    documentTitle: 'INDEPENDENT CONTRACTOR AGREEMENT',
    intro: 'This Agreement is made on {date} between:\n\nClient: {partyA}\nContractor: {partyB}',
    terms: [
      { id: 'ic1', title: 'Services', content: 'Contractor agrees to perform the services described herein as an independent contractor, not as an employee of Client. Contractor will determine the method, details, and means of performing the services.' },
      { id: 'ic2', title: 'Compensation', content: 'Client will pay Contractor for services rendered according to the terms mutually agreed upon in writing. Contractor shall be responsible for all taxes, including Social Security, Medicare, and income taxes.' },
      { id: 'ic3', title: 'Intellectual Property', content: "Any work product generated by the Contractor in the execution of this agreement shall be the exclusive property of the Client. Contractor agrees to execute any documents necessary to perfect Client's title to the work product." },
      { id: 'ic4', title: 'Termination', content: 'Either party may terminate this Agreement at any time with written notice.' }
    ]
  },
  project_start: {
    name: 'Project Start (SOW)',
    documentTitle: 'STATEMENT OF WORK (PROJECT START)',
    intro: 'This Statement of Work ("SOW") is entered into on {date} by and between:\n\nClient: {partyA}\nAgency/Developer: {partyB}',
    terms: [
      { id: 'ps1', title: 'Scope of Work', content: 'The Agency/Developer shall deliver the services and features outlined in the approved project proposal. Any deviation from the defined scope requires a written Change Request approved by both parties.' },
      { id: 'ps2', title: 'Timeline & Deliverables', content: 'Work shall commence immediately upon signing this Agreement. Deliverables will be provided according to the milestone schedule defined during the project kickoff.' },
      { id: 'ps3', title: 'Payment Terms', content: 'Client agrees to pay the project fee in installments: 50% upfront to commence work, and 50% upon final delivery and acceptance of the completed project.' },
      { id: 'ps4', title: 'Acceptance & Revisions', content: 'Client shall have a period of 10 business days to review and accept the final deliverables. Up to two (2) rounds of minor revisions are included in the scope.' }
    ]
  },
  oss_cla: {
    name: 'OSS Contributor (CLA)',
    documentTitle: 'CONTRIBUTOR LICENSE AGREEMENT',
    intro: 'This Contributor License Agreement ("Agreement") is agreed to by the Contributor on {date}.\n\nProject Sponsor: {partyA}\nContributor: {partyB}',
    terms: [
      { id: 'cla1', title: 'Grant of Copyright License', content: 'Subject to the terms and conditions of this Agreement, You hereby grant to the Project Sponsor and to recipients of software distributed by the Project Sponsor a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.' },
      { id: 'cla2', title: 'Grant of Patent License', content: 'Subject to the terms and conditions of this Agreement, You hereby grant to the Project Sponsor a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work.' },
      { id: 'cla3', title: 'Representations', content: 'You represent that You are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer.' }
    ]
  }
};

type TemplateType = keyof typeof TEMPLATES;

export default function LegalGeneratorClient() {
  const docId = useId().replace(/:/g, '').toUpperCase();
  const [viewMode, setViewMode] = useState<'2d' | '3d'>('2d');

  const [template, setTemplate] = useState<TemplateType>('nda');
  const [partyA, setPartyA] = useState('');
  const [partyB, setPartyB] = useState('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);

  // Dynamic Document Content
  const [documentTitle, setDocumentTitle] = useState(TEMPLATES.nda.documentTitle);
  const [intro, setIntro] = useState(TEMPLATES.nda.intro);
  const [terms, setTerms] = useState<Term[]>(TEMPLATES.nda.terms);

  const [signatureData, setSignatureData] = useState<string | null>(null);
  const sigCanvasRef = useRef<SignatureCanvas>(null);

  const previewRef = useRef<HTMLDivElement>(null);
  const [textureUrl, setTextureUrl] = useState<string>('');
  const [isGenerating3D, setIsGenerating3D] = useState(false);
  const [aspect, setAspect] = useState<number>(1.414);

  const handleTemplateChange = (key: TemplateType) => {
    setTemplate(key);
    setDocumentTitle(TEMPLATES[key].documentTitle);
    setIntro(TEMPLATES[key].intro);
    setTerms(TEMPLATES[key].terms.map(t => ({ ...t }))); // Deep clone to avoid mutating standard template
  };

  const addTerm = () => {
    setTerms([...terms, { id: Math.random().toString(36).substring(7), title: 'New Clause', content: '' }]);
  };

  const updateTerm = (id: string, field: keyof Term, value: string) => {
    setTerms(terms.map(t => t.id === id ? { ...t, [field]: value } : t));
  };

  const deleteTerm = (id: string) => {
    setTerms(terms.filter(t => t.id !== id));
  };

  const generateTexture = async () => {
    if (!previewRef.current) return;
    setIsGenerating3D(true);
    try {
      // toJpeg is significantly faster than toPng (no alpha channel processing)
      // pixelRatio: 1 provides maximum performance for large DOM nodes
      const dataUrl = await toJpeg(previewRef.current, { 
        quality: 0.8, 
        pixelRatio: 1.0,
        skipAutoScale: true,
        backgroundColor: '#ffffff'
      });
      setTextureUrl(dataUrl);
      
      const rect = previewRef.current.getBoundingClientRect();
      if (rect.width && rect.height) {
        setAspect(rect.height / rect.width);
      }
    } catch (err) {
      console.error('Failed to generate texture', err);
    } finally {
      setIsGenerating3D(false);
    }
  };

  useEffect(() => {
    if (viewMode === '3d') {
      const timer = setTimeout(generateTexture, 800);
      return () => clearTimeout(timer);
    }
  }, [viewMode, partyA, partyB, date, template, signatureData, documentTitle, intro, terms]);

  const { registerPage, unregisterPage } = useAgent();

  useEffect(() => {
    registerPage(
      'Legal Generator',
      `{
        "template": "nda | contractor | project_start | oss_cla",
        "partyA": "string",
        "partyB": "string",
        "date": "YYYY-MM-DD",
        "documentTitle": "string",
        "intro": "string",
        "terms": [{"title": "string", "content": "string"}]
      }`,
      (data: any) => {
        if (data.template && Object.keys(TEMPLATES).includes(data.template)) {
          setTemplate(data.template as keyof typeof TEMPLATES);
        }
        if (data.partyA) setPartyA(data.partyA);
        if (data.partyB) setPartyB(data.partyB);
        if (data.date) setDate(data.date);
        if (data.documentTitle) setDocumentTitle(data.documentTitle);
        if (data.intro) setIntro(data.intro);
        
        if (Array.isArray(data.terms)) {
          setTerms(data.terms.map((t: any, i: number) => ({
            id: `agent-term-${i}`,
            title: t.title || '',
            content: t.content || ''
          })));
        }
      }
    );
    return () => unregisterPage();
  }, [registerPage, unregisterPage]);

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow || !previewRef.current) return;
    
    const contentHtml = previewRef.current.innerHTML;
    
    printWindow.document.write(`
      <html>
        <head>
          <title>${documentTitle}</title>
          <style>
            body { font-family: "Times New Roman", Times, serif; line-height: 1.6; padding: 2rem; max-width: 800px; margin: 0 auto; color: #000; }
            h1 { font-size: 1.5rem; font-weight: bold; text-transform: uppercase; border-bottom: 1px solid #000; padding-bottom: 0.5rem; margin-bottom: 2rem; text-align: center; }
            p { margin-bottom: 1rem; text-align: justify; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; margin-top: 4rem; padding-top: 2rem; border-top: 1px solid #eaeaea; }
            .border-b { border-bottom: 1px solid #666; height: 4rem; position: relative; display: flex; align-items: flex-end; }
            .italic { font-style: italic; color: #666; }
            .font-bold { font-weight: bold; }
            .text-sm { font-size: 0.875rem; }
            .text-xs { font-size: 0.75rem; color: #666; margin-top: 0.5rem; }
            .uppercase { text-transform: uppercase; }
            img { max-height: 4rem; max-width: 100%; object-fit: contain; }
            .footer { position: fixed; bottom: 2rem; left: 0; right: 0; text-align: center; font-size: 0.75rem; color: #999; border-top: 1px solid #eaeaea; padding-top: 1rem; }
            @media print {
              body { padding: 0; }
              .footer { position: fixed; bottom: 0; }
            }
          </style>
        </head>
        <body>
          ${contentHtml}
        </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  const handleClearSignature = () => {
    sigCanvasRef.current?.clear();
    setSignatureData(null);
  };

  const handleSaveSignature = () => {
    if (sigCanvasRef.current && !sigCanvasRef.current.isEmpty()) {
      setSignatureData(sigCanvasRef.current.getTrimmedCanvas().toDataURL('image/png'));
    }
  };

  // Convert newline to <br/> and wrap paragraphs
  const renderLegalText = (text: string) => {
    // Replace placeholders
    const processedText = text
      .replace(/{partyA}/g, partyA || '[Party A Name]')
      .replace(/{partyB}/g, partyB || '[Party B Name]')
      .replace(/{date}/g, date);

    return processedText.trim().split('\n\n').map((paragraph, idx) => (
      <p key={idx} className="mb-4 text-justify whitespace-pre-wrap leading-relaxed">
        {paragraph.trim()}
      </p>
    ));
  };

  return (
    <div className="flex flex-col md:flex-row md:h-screen md:overflow-hidden bg-background">
      {/* Left Sidebar - Form Editor */}
      <div className="w-full md:w-[320px] lg:w-[400px] xl:w-[460px] border-b md:border-b-0 md:border-r border-border/50 bg-surface/30 backdrop-blur-md flex flex-col md:h-full z-10 overflow-y-auto custom-scrollbar">
        <div className="p-6 border-b border-border/50 sticky top-0 bg-surface/80 backdrop-blur-md z-20">
          <div className="flex items-center gap-3 mb-6">
            <FileSignature className="w-6 h-6 text-primary shrink-0" />
            <div>
              <h2 className="text-lg font-bold tracking-tight">Legal Agreement</h2>
              <p className="text-xs text-foreground/60">Generate and sign legal docs</p>
            </div>
          </div>

          {/* View Toggle */}
          <div className="flex bg-foreground/5 p-1 rounded-xl">
            <button
              onClick={() => setViewMode('2d')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium transition-all ${viewMode === '2d' ? 'bg-background shadow-sm text-foreground' : 'text-foreground/60 hover:text-foreground'}`}
            >
              <AlignLeft className="w-4 h-4" /> 2D Preview
            </button>
            <button
              onClick={() => setViewMode('3d')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium transition-all ${viewMode === '3d' ? 'bg-background shadow-sm text-foreground' : 'text-foreground/60 hover:text-foreground'}`}
            >
              <Eye className="w-4 h-4" /> 3D View
            </button>
          </div>
        </div>

        <div className="p-6 space-y-8">
          {/* Template Selection */}
          <div className="space-y-3">
            <label className="text-xs font-bold uppercase tracking-wider text-foreground/60 flex items-center gap-2">
              <FileText className="w-3 h-3" /> Standard Templates
            </label>
            <div className="grid grid-cols-2 gap-2">
              {(Object.keys(TEMPLATES) as TemplateType[]).map((key) => (
                <button
                  key={key}
                  onClick={() => handleTemplateChange(key)}
                  className={`px-3 py-2 text-xs rounded-xl border text-left transition-all ${template === key ? 'border-primary bg-primary/10 text-primary font-bold' : 'border-border/50 bg-foreground/5 text-foreground/70 hover:border-foreground/20'}`}
                >
                  {TEMPLATES[key].name}
                </button>
              ))}
            </div>
          </div>

          {/* Details */}
          <div className="space-y-4">
            <label className="text-xs font-bold uppercase tracking-wider text-foreground/60 flex items-center gap-2">
              <User className="w-3 h-3" /> Document Parties
            </label>

            <div className="space-y-3">
              <input
                type="text"
                name="partyA"
                placeholder="Party A (Client/Disclosing Party)"
                value={partyA}
                onChange={(e) => setPartyA(e.target.value)}
                className="w-full bg-foreground/5 border border-border/50 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all placeholder:text-foreground/30"
              />
              <input
                type="text"
                name="partyB"
                placeholder="Party B (Contractor/Receiving Party)"
                value={partyB}
                onChange={(e) => setPartyB(e.target.value)}
                className="w-full bg-foreground/5 border border-border/50 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all placeholder:text-foreground/30"
              />
              <div className="relative">
                <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-foreground/40" />
                <input
                  type="date"
                  name="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="w-full bg-foreground/5 border border-border/50 rounded-xl pl-10 pr-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all text-foreground/80"
                />
              </div>
            </div>
          </div>

          <div className="h-px bg-border/50 w-full" />

          {/* Document Content Editor */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <label className="text-xs font-bold uppercase tracking-wider text-foreground/60 flex items-center gap-2">
                <AlignLeft className="w-3 h-3" /> Content Editor
              </label>
            </div>

            <div className="space-y-3">
              <label className="text-[11px] font-semibold text-foreground/50 uppercase tracking-wider block">Document Title</label>
              <input name="documentTitle"
                type="text"
                value={documentTitle}
                onChange={(e) => setDocumentTitle(e.target.value)}
                className="w-full bg-foreground/5 border border-border/50 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all font-bold"
              />
            </div>

            <div className="space-y-3">
              <label className="text-[11px] font-semibold text-foreground/50 uppercase tracking-wider block">Introduction Text</label>
              <textarea name="intro"
                value={intro}
                onChange={(e) => setIntro(e.target.value)}
                rows={3}
                className="w-full bg-foreground/5 border border-border/50 rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 transition-all resize-y custom-scrollbar"
              />
              <p className="text-[10px] text-foreground/40 leading-relaxed">
                Use <code className="bg-foreground/10 px-1 py-0.5 rounded">{'{partyA}'}</code>, <code className="bg-foreground/10 px-1 py-0.5 rounded">{'{partyB}'}</code>, and <code className="bg-foreground/10 px-1 py-0.5 rounded">{'{date}'}</code> as variables.
              </p>
            </div>

            <div className="space-y-4 pt-4">
              <div className="flex items-center justify-between">
                <label className="text-[11px] font-semibold text-foreground/50 uppercase tracking-wider block">Terms & Conditions</label>
                <button
                  onClick={addTerm}
                  className="flex items-center gap-1 text-[11px] font-bold text-primary hover:bg-primary/10 px-2 py-1 rounded-md transition-colors"
                >
                  <Plus className="w-3 h-3" /> Add Term
                </button>
              </div>

              <div className="space-y-4">
                <AnimatePresence>
                  {terms.map((term, index) => (
                    <motion.div
                      key={term.id}
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="bg-foreground/5 border border-border/50 rounded-xl p-4 space-y-3 relative group"
                    >
                      <button
                        onClick={() => deleteTerm(term.id)}
                        className="absolute right-3 top-3 text-foreground/30 hover:text-rose-500 transition-colors opacity-0 group-hover:opacity-100"
                        title="Remove Term"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                      <div className="pr-6">
                        <input name="term.title"
                          type="text"
                          value={term.title}
                          onChange={(e) => updateTerm(term.id, 'title', e.target.value)}
                          placeholder="Term Title (e.g. Compensation)"
                          className="w-full bg-transparent border-b border-border/50 px-1 py-1 text-sm font-bold focus:outline-none focus:border-primary transition-all mb-2"
                        />
                        <textarea name="term.content"
                          value={term.content}
                          onChange={(e) => updateTerm(term.id, 'content', e.target.value)}
                          placeholder="Enter the legal clause details here..."
                          rows={3}
                          className="w-full bg-transparent border-none px-1 py-1 text-[13px] leading-relaxed text-foreground/70 focus:outline-none focus:text-foreground transition-all resize-y custom-scrollbar"
                        />
                      </div>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            </div>
          </div>

          <div className="h-px bg-border/50 w-full" />

          {/* Signature Canvas */}
          <div className="space-y-3 pb-8">
            <label className="text-xs font-bold uppercase tracking-wider text-foreground/60 flex items-center gap-2">
              <FileSignature className="w-3 h-3" /> Digital Signature
            </label>
            <div className="border border-border/50 rounded-xl bg-white overflow-hidden shadow-inner">
              <SignatureCanvas
                ref={sigCanvasRef}
                penColor="black"
                canvasProps={{ className: 'w-full h-[150px] cursor-crosshair' }}
                onEnd={handleSaveSignature}
              />
            </div>
            <div className="flex gap-2">
              <button
                onClick={handleClearSignature}
                className="flex-1 px-4 py-2 bg-foreground/5 hover:bg-foreground/10 text-foreground/70 rounded-lg text-sm font-medium transition-colors flex items-center justify-center gap-2"
              >
                <Eraser className="w-4 h-4" /> Clear
              </button>
              <button
                onClick={handleSaveSignature}
                className="flex-1 px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded-lg text-sm font-bold transition-colors flex items-center justify-center gap-2 shadow-md shadow-primary/20"
              >
                <Save className="w-4 h-4" /> Save Signature
              </button>
            </div>
            {signatureData && (
              <p className="text-xs text-emerald-500 font-medium text-center flex items-center justify-center gap-1">
                <FileSignature className="w-3 h-3" /> Signature captured successfully
              </p>
            )}
          </div>
        </div>
      </div>

      {/* Right Content - Document Preview */}
      <div className="flex-1 relative bg-foreground/5 overflow-hidden flex flex-col min-h-[500px] md:h-screen">
        {/* Header Actions */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border/50 bg-surface/50 backdrop-blur-md sticky top-0 z-20">
          <h3 className="text-sm font-semibold text-foreground/80 tracking-wide uppercase">Document Preview</h3>
          <div className="flex items-center gap-4">
            <button 
              onClick={handlePrint}
              className="flex items-center gap-2 px-4 py-1.5 bg-background border border-border/50 hover:bg-surface/80 rounded-lg text-sm font-medium transition-all shadow-sm"
            >
              <Download className="w-4 h-4" /> Print / Save PDF
            </button>
          </div>
        </div>

        <div className={`flex-1 overflow-y-auto p-8 flex justify-center items-start custom-scrollbar ${viewMode === '3d' ? 'absolute opacity-0 pointer-events-none -z-10 w-full h-full' : 'relative z-10'}`}>
          {/* The A4 Document */}
          <div
            ref={previewRef}
            className="bg-white w-full max-w-[800px] h-fit shadow-2xl origin-top rounded-sm flex flex-col p-12 relative"
            style={{ minHeight: '1131px', color: '#000000', fontFamily: '"Times New Roman", Times, serif' }}
          >
            {/* Document Header & Intro */}
            <div className="text-center mb-10">
              <h1 className="text-xl font-bold uppercase tracking-wide border-b border-black pb-2 inline-block">
                {documentTitle || 'LEGAL AGREEMENT'}
              </h1>
            </div>

            <div className="text-[15px] max-w-full mb-8">
              {renderLegalText(intro)}
            </div>

            {/* Document Terms */}
            <div className="text-[15px] max-w-full space-y-6">
              {terms.map((term, index) => (
                <div key={term.id} className="text-justify leading-relaxed">
                  <span className="font-bold mr-2">{index + 1}. {term.title}.</span>
                  <span>{term.content}</span>
                </div>
              ))}
            </div>

            {/* Closing statement */}
            <div className="mt-8 text-[15px] max-w-full italic">
              IN WITNESS WHEREOF, the parties hereto have executed this Agreement as of the Effective Date.
            </div>

            {/* Signature Block */}
            <div className="mt-16 pt-8 grid grid-cols-2 gap-12">
              <div>
                <div className="text-sm font-bold mb-4 uppercase tracking-wider text-gray-500">Party A</div>
                <div className="border-b border-gray-400 h-16 relative">
                  <span className="absolute bottom-2 left-0 text-gray-800 italic">{partyA || '________________________'}</span>
                </div>
                <div className="text-xs text-gray-500 mt-2">Name: {partyA}</div>
                <div className="text-xs text-gray-500 mt-1">Date: {date}</div>
              </div>
              <div>
                <div className="text-sm font-bold mb-4 uppercase tracking-wider text-gray-500">Party B</div>
                <div className="border-b border-gray-400 h-16 relative flex items-end">
                  {signatureData ? (
                    <img src={signatureData} alt="Signature" className="h-16 max-w-full object-contain pb-1" />
                  ) : (
                    <span className="text-gray-400 italic mb-2">Sign using the canvas on the left</span>
                  )}
                </div>
                <div className="text-xs text-gray-500 mt-2">Name: {partyB}</div>
                <div className="text-xs text-gray-500 mt-1">Date: {signatureData ? date : ''}</div>
              </div>
            </div>

            {/* Footer */}
            <div className="text-center text-xs text-gray-400 border-t border-gray-100 pt-4 mt-auto w-full">
              Generated securely by Hephaestus Code-to-Legal • Document ID: {docId}
            </div>
          </div>
        </div>
        
        {viewMode === '3d' && (
          <div className="absolute inset-0 w-full h-full cursor-grab active:cursor-grabbing z-10">
            {isGenerating3D && (
              <div className="absolute inset-0 bg-background/50 backdrop-blur-sm z-20 flex items-center justify-center">
                <div className="flex flex-col items-center gap-4 bg-surface p-6 rounded-2xl shadow-xl border border-border/50">
                  <span className="inline-block w-8 h-8 border-4 border-primary/30 border-t-primary rounded-full animate-spin" />
                  <p className="text-sm font-bold text-foreground/70">Rendering 3D Document...</p>
                </div>
              </div>
            )}
            <ThreeDViewer textureUrl={textureUrl} aspect={aspect} />
          </div>
        )}
      </div>
    </div>
  );
}
